version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env.production
    ports:
      - "9002:3001"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: /api
    depends_on:
      - backend
    ports:
      - "9001:80"
    restart: unless-stopped
